# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T09:37:43+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, RootModel


class Inning(BaseModel):
    AwayTeamRuns: Optional[int] = None
    GameID: Optional[int] = None
    HomeTeamRuns: Optional[int] = None
    InningID: Optional[int] = None
    InningNumber: Optional[int] = None


class Pitch(BaseModel):
    Ball: Optional[bool] = None
    BallsBeforePitch: Optional[int] = None
    Foul: Optional[bool] = None
    HitterID: Optional[int] = None
    Looking: Optional[bool] = None
    Outs: Optional[int] = None
    PitchID: Optional[int] = None
    PitchNumberThisAtBat: Optional[int] = None
    PitcherID: Optional[int] = None
    PlayID: Optional[int] = None
    Strike: Optional[bool] = None
    StrikesBeforePitch: Optional[int] = None
    Swinging: Optional[bool] = None


class Play(BaseModel):
    AtBat: Optional[bool] = None
    AwayTeamRuns: Optional[int] = None
    Balls: Optional[int] = None
    Description: Optional[str] = None
    Error: Optional[bool] = None
    Hit: Optional[bool] = None
    HitterBatHand: Optional[str] = None
    HitterID: Optional[int] = None
    HitterName: Optional[str] = None
    HitterPosition: Optional[str] = None
    HitterTeamID: Optional[int] = None
    HomeTeamRuns: Optional[int] = None
    InningBatterNumber: Optional[int] = None
    InningHalf: Optional[str] = None
    InningID: Optional[int] = None
    InningNumber: Optional[int] = None
    NumberOfOutsOnPlay: Optional[int] = None
    Out: Optional[bool] = None
    Outs: Optional[int] = None
    PitchNumberThisAtBat: Optional[int] = None
    PitcherID: Optional[int] = None
    PitcherName: Optional[str] = None
    PitcherTeamID: Optional[int] = None
    PitcherThrowHand: Optional[str] = None
    Pitches: Optional[List[Pitch]] = None
    PlayID: Optional[int] = None
    PlayNumber: Optional[int] = None
    Result: Optional[str] = None
    Runner1ID: Optional[int] = None
    Runner2ID: Optional[int] = None
    Runner3ID: Optional[int] = None
    RunsBattedIn: Optional[int] = None
    Sacrifice: Optional[bool] = None
    Strikeout: Optional[bool] = None
    Strikes: Optional[int] = None
    Updated: Optional[str] = None
    Walk: Optional[bool] = None


class Series(BaseModel):
    AwayTeamWins: Optional[int] = None
    GameNumber: Optional[int] = None
    HomeTeamWins: Optional[int] = None
    MaxLength: Optional[int] = None


class Format(Enum):
    XML = 'XML'
    JSON = 'JSON'


class Game(BaseModel):
    Attendance: Optional[int] = None
    AwayRotationNumber: Optional[int] = None
    AwayTeam: Optional[str] = None
    AwayTeamErrors: Optional[int] = None
    AwayTeamHits: Optional[int] = None
    AwayTeamID: Optional[int] = None
    AwayTeamMoneyLine: Optional[int] = None
    AwayTeamProbablePitcherID: Optional[int] = None
    AwayTeamRuns: Optional[int] = None
    AwayTeamStartingPitcher: Optional[str] = None
    AwayTeamStartingPitcherID: Optional[int] = None
    Balls: Optional[int] = None
    Channel: Optional[str] = None
    CurrentHitter: Optional[str] = None
    CurrentHitterID: Optional[int] = None
    CurrentHittingTeamID: Optional[int] = None
    CurrentPitcher: Optional[str] = None
    CurrentPitcherID: Optional[int] = None
    CurrentPitchingTeamID: Optional[int] = None
    DateTime: Optional[str] = None
    DateTimeUTC: Optional[str] = None
    Day: Optional[str] = None
    DueUpHitterID1: Optional[int] = None
    DueUpHitterID2: Optional[int] = None
    DueUpHitterID3: Optional[int] = None
    ForecastDescription: Optional[str] = None
    ForecastTempHigh: Optional[int] = None
    ForecastTempLow: Optional[int] = None
    ForecastWindChill: Optional[int] = None
    ForecastWindDirection: Optional[int] = None
    ForecastWindSpeed: Optional[int] = None
    GameEndDateTime: Optional[str] = None
    GameID: Optional[int] = None
    GlobalAwayTeamID: Optional[int] = None
    GlobalGameID: Optional[int] = None
    GlobalHomeTeamID: Optional[int] = None
    HomeRotationNumber: Optional[int] = None
    HomeTeam: Optional[str] = None
    HomeTeamErrors: Optional[int] = None
    HomeTeamHits: Optional[int] = None
    HomeTeamID: Optional[int] = None
    HomeTeamMoneyLine: Optional[int] = None
    HomeTeamProbablePitcherID: Optional[int] = None
    HomeTeamRuns: Optional[int] = None
    HomeTeamStartingPitcher: Optional[str] = None
    HomeTeamStartingPitcherID: Optional[int] = None
    Inning: Optional[int] = None
    InningDescription: Optional[str] = None
    InningHalf: Optional[str] = None
    Innings: Optional[List[Inning]] = None
    IsClosed: Optional[bool] = None
    LastPlay: Optional[str] = None
    LosingPitcher: Optional[str] = None
    LosingPitcherID: Optional[int] = None
    NeutralVenue: Optional[bool] = None
    Outs: Optional[int] = None
    OverPayout: Optional[int] = None
    OverUnder: Optional[float] = None
    PointSpread: Optional[float] = None
    PointSpreadAwayTeamMoneyLine: Optional[int] = None
    PointSpreadHomeTeamMoneyLine: Optional[int] = None
    RescheduledFromGameID: Optional[int] = None
    RescheduledGameID: Optional[int] = None
    RunnerOnFirst: Optional[bool] = None
    RunnerOnSecond: Optional[bool] = None
    RunnerOnThird: Optional[bool] = None
    SavingPitcher: Optional[str] = None
    SavingPitcherID: Optional[int] = None
    Season: Optional[int] = None
    SeasonType: Optional[int] = None
    SeriesInfo: Optional[Series] = None
    StadiumID: Optional[int] = None
    Status: Optional[str] = None
    Strikes: Optional[int] = None
    UnderPayout: Optional[int] = None
    Updated: Optional[str] = None
    WinningPitcher: Optional[str] = None
    WinningPitcherID: Optional[int] = None


class PlayByPlay(BaseModel):
    Game_1: Optional[Game] = Field(None, alias='Game')
    Plays: Optional[List[Play]] = None


class FieldFormatPlayByPlayDeltaDateMinutesGetResponse(RootModel[List[PlayByPlay]]):
    root: List[PlayByPlay]
